# -*- coding: utf-8 -*-
"""「計算思維」的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byOdqC7B3nShZYCRET7ZveOiDuXcgFqq
"""

file_path <- '/content/未命名的試算表 - 工作表1.csv'

data <- read.csv(file_path)

install.packages("ggplot2")
install.packages("forecast")
library(ggplot2)
library(forecast)

head(data)

#線性迴歸結果(Carbon_Emissions)
model <- lm(Carbon_Emissions ~ Year, data = data)
summary(model)

# 創建一個包含2023到2027年的數據框
future_years <- data.frame(Year = 2023:2027)

# 使用模型進行預測
predictions <- predict(model, newdata = future_years)
future_data <- cbind(future_years, Carbon_Emissions = predictions)
print(future_data)

#預測走向折線圖(Carbon_Emissions)
ggplot() +
  geom_point(data = data, aes(x = Year, y = Carbon_Emissions), color = "blue") +
  geom_line(data = data, aes(x = Year, y = Carbon_Emissions), color = "blue") +
  geom_point(data = future_data, aes(x = Year, y = Carbon_Emissions), color = "red") +
  geom_line(data = future_data, aes(x = Year, y = Carbon_Emissions), color = "red") +
  labs(title = "數據預測",
       x = "年份",
       y = "值") +
  theme_minimal()